# Generated by Django 5.0.4 on 2024-04-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='other_name',
        ),
    ]
