# Generated by Django 5.0.4 on 2024-05-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_user_is_admin_user_is_student_alter_user_email_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
